pub struct ShortcutDef {
    pub action_id: &'static str,
    pub label: &'static str,
    pub description: &'static str,
    pub category: &'static str,
    pub default_binding: &'static str,
    pub is_global: bool,
}

pub const DEFAULT_SHORTCUTS: &[ShortcutDef] = &[
    // ── Global shortcuts ──────────────────────────
    ShortcutDef {
        action_id: "global.toggle_caption",
        label: "Start/Stop Live Caption",
        description: "Toggle live captioning from any app",
        category: "global",
        default_binding: "CmdOrCtrl+Shift+C",
        is_global: true,
    },
    ShortcutDef {
        action_id: "global.quick_review",
        label: "Quick Review",
        description: "Start a review session from any app",
        category: "global",
        default_binding: "CmdOrCtrl+Shift+R",
        is_global: true,
    },
    ShortcutDef {
        action_id: "global.show_app",
        label: "Show/Hide App",
        description: "Bring FlexiDesk to front or minimize",
        category: "global",
        default_binding: "CmdOrCtrl+Shift+F",
        is_global: true,
    },
    // ── Navigation ────────────────────────────────
    ShortcutDef {
        action_id: "nav.dashboard",
        label: "Go to Dashboard",
        description: "Navigate to Dashboard page",
        category: "navigation",
        default_binding: "CmdOrCtrl+1",
        is_global: false,
    },
    ShortcutDef {
        action_id: "nav.review",
        label: "Go to Review",
        description: "Navigate to Review/SRS page",
        category: "navigation",
        default_binding: "CmdOrCtrl+2",
        is_global: false,
    },
    ShortcutDef {
        action_id: "nav.reading",
        label: "Go to Reading",
        description: "Navigate to Reading page",
        category: "navigation",
        default_binding: "CmdOrCtrl+3",
        is_global: false,
    },
    ShortcutDef {
        action_id: "nav.tutor",
        label: "Go to Tutor",
        description: "Navigate to Tutor page",
        category: "navigation",
        default_binding: "CmdOrCtrl+4",
        is_global: false,
    },
    ShortcutDef {
        action_id: "nav.caption",
        label: "Go to Caption",
        description: "Navigate to Caption page",
        category: "navigation",
        default_binding: "CmdOrCtrl+5",
        is_global: false,
    },
    ShortcutDef {
        action_id: "nav.writing",
        label: "Go to Writing",
        description: "Navigate to Writing page",
        category: "navigation",
        default_binding: "CmdOrCtrl+6",
        is_global: false,
    },
    ShortcutDef {
        action_id: "nav.pronunciation",
        label: "Go to Pronunciation",
        description: "Navigate to Pronunciation page",
        category: "navigation",
        default_binding: "CmdOrCtrl+7",
        is_global: false,
    },
    ShortcutDef {
        action_id: "nav.exam",
        label: "Go to Exam",
        description: "Navigate to Exam page",
        category: "navigation",
        default_binding: "CmdOrCtrl+8",
        is_global: false,
    },
    ShortcutDef {
        action_id: "nav.podcast",
        label: "Go to Podcast",
        description: "Navigate to Podcast page",
        category: "navigation",
        default_binding: "CmdOrCtrl+9",
        is_global: false,
    },
    ShortcutDef {
        action_id: "nav.settings",
        label: "Go to Settings",
        description: "Navigate to Settings page",
        category: "navigation",
        default_binding: "CmdOrCtrl+,",
        is_global: false,
    },
    // ── Review shortcuts ──────────────────────────
    ShortcutDef {
        action_id: "review.show_answer",
        label: "Show Answer",
        description: "Reveal the card answer",
        category: "review",
        default_binding: "Space",
        is_global: false,
    },
    ShortcutDef {
        action_id: "review.rate_again",
        label: "Rate: Again",
        description: "Rate current card as Again (1)",
        category: "review",
        default_binding: "1",
        is_global: false,
    },
    ShortcutDef {
        action_id: "review.rate_hard",
        label: "Rate: Hard",
        description: "Rate current card as Hard (2)",
        category: "review",
        default_binding: "2",
        is_global: false,
    },
    ShortcutDef {
        action_id: "review.rate_good",
        label: "Rate: Good",
        description: "Rate current card as Good (3)",
        category: "review",
        default_binding: "3",
        is_global: false,
    },
    ShortcutDef {
        action_id: "review.rate_easy",
        label: "Rate: Easy",
        description: "Rate current card as Easy (4)",
        category: "review",
        default_binding: "4",
        is_global: false,
    },
    // ── Podcast/Audio ─────────────────────────────
    ShortcutDef {
        action_id: "audio.play_pause",
        label: "Play/Pause",
        description: "Toggle audio playback",
        category: "podcast",
        default_binding: "Space",
        is_global: false,
    },
    ShortcutDef {
        action_id: "audio.seek_back",
        label: "Seek Back 5s",
        description: "Rewind audio 5 seconds",
        category: "podcast",
        default_binding: "ArrowLeft",
        is_global: false,
    },
    ShortcutDef {
        action_id: "audio.seek_forward",
        label: "Seek Forward 5s",
        description: "Fast-forward audio 5 seconds",
        category: "podcast",
        default_binding: "ArrowRight",
        is_global: false,
    },
    // ── General ───────────────────────────────────
    ShortcutDef {
        action_id: "general.search",
        label: "Search",
        description: "Open global search",
        category: "general",
        default_binding: "CmdOrCtrl+K",
        is_global: false,
    },
    ShortcutDef {
        action_id: "general.toggle_sidebar",
        label: "Toggle Sidebar",
        description: "Show/hide the sidebar",
        category: "general",
        default_binding: "CmdOrCtrl+B",
        is_global: false,
    },
];
